# for a complete reference, visit
# https://github.com/Macchina-CLI/macchina/wiki/Theme-Documentation

spacing = 3
padding = 0
hide_ascii = false
prefer_small_ascii = false
separator = ""
key_color = "Blue"
separator_color = "White"

[palette]
type = "Dark"
glyph = "色"
spacing = 3
visible = true

[bar]
glyph = "ߋ"
symbol_open = '['
symbol_close = ']'
visible = true
hide_delimiters = true

[box]
title = " feefs "
border = "rounded"
visible = true

[box.inner_margin]
x = 2
y = 1

[custom_ascii]
path = "~/.config/macchina/ascii/apple.ascii"

[keys]
host = "Host"
kernel = "Kernel"
battery = "Battery"
os = "OS"
machine = "Machine"
de = "DE"
wm = "WM"
distro = "Distro"
terminal = "Terminal"
shell = "Shell"
packages = "Packages"
uptime = "Uptime"
local_ip = "Local IP"
memory = "Memory"
backlight = "Brightness"
resolution = "Resolution"
cpu = "CPU"
cpu_load = "CPU %"
