# Specifies the network interface to use for the LocalIP readout
interface = "en0"

# Lengthen uptime output
long_uptime = false

# Lengthen shell output
long_shell = false

# Lengthen kernel output
long_kernel = true

# Toggle between displaying the current shell or your user's default one.
current_shell = true

theme = "Custom"

# Displays only the specified readouts.
# Accepted values (case-sensitive):
#   - Host
#   - Machine
#   - Kernel
#   - Distribution
#   - OperatingSystem
#   - DesktopEnvironment
#   - WindowManager
#   - Resolution
#   - Backlight
#   - Packages
#   - LocalIP
#   - Terminal
#   - Shell
#   - Uptime
#   - Processor
#   - ProcessorLoad
#   - Memory
#   - Battery
# Example:
#   show = ["Battery", "Memory", ...]
show = ["Kernel", "OperatingSystem", "Packages", "Terminal", "Uptime", "Processor", "ProcessorLoad", "Memory", "Battery"]
